### ISSUE TITLE
Error upon activation with the most recent Animation Nodes commit 

### ISSUE THREAD

**Issue by meikasahara** [harisreedhar/an_bluefox_extension#7]
The following error message appears and the addon cannot be activated (using Xubuntu 20.04 and Blender 2.93)

```
Traceback (most recent call last):
  File "/home/Downloads/blender-2.93.0-a/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/.config/blender/2.93/scripts/addons/an_bluefox_extension/__init__.py", line 44, in <module>
    auto_load.init()
  File "/home/.config/blender/2.93/scripts/addons/an_bluefox_extension/auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "/home/.config/blender/2.93/scripts/addons/an_bluefox_extension/auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "/home/.config/blender/2.93/scripts/addons/an_bluefox_extension/auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/home/Downloads/blender-2.93.0-a/2.93/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "an_bluefox_extension/nodes/color/c_utils.pyx", line 1, in init an_bluefox_extension.nodes.color.c_utils
ValueError: animation_nodes.data_structures.meshes.mesh_data.Mesh size changed, may indicate binary incompatibility. Expected 72 from C header, got 56 from PyObject
```

**Comment by harisreedhar** [comment]
@meikasahara It is fixed. Thanks for the report

**Comment by meikasahara** [comment]
Thank you! Would it be possible to port the Miscellaneous section (Specifically the fibonacci and lorenz attractor nodes from your previous build of animation nodes (AN_BLUEFOX)? I used to compile it porting the most recent updates from the main fork but after this commit it can no longer be installed, returning the same error as this one.

**Comment by harisreedhar** [comment]
@meikasahara The old addon is not updated for blender 2.93. It is depricated.
For now you can download this zip [miscellaneous.zip](https://github.com/harisreedhar/an_bluefox_extension/files/6318411/miscellaneous.zip) and unzip it inside addon location ``/addons/an_bluefox_extension/nodes``.
The nodes will not show on menu but you can use search to find these nodes.

**Comment by meikasahara** [comment]
Thank you very much!
